import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

export async function buildReceiptPdf(input: {
  receiptNo: string;
  societyName: string;
  memberName: string;
  amount: number;
  fiscalYear: number;
  paidAt?: Date | null;
}) {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([595, 842]);
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);

  page.drawText("Receipt", { x: 240, y: 790, size: 20, font: bold, color: rgb(0.1, 0.1, 0.1) });
  page.drawText(`No: ${input.receiptNo}`, { x: 60, y: 750, size: 12, font });
  page.drawText(`Society: ${input.societyName}`, { x: 60, y: 720, size: 12, font });
  page.drawText(`Member: ${input.memberName}`, { x: 60, y: 690, size: 12, font });
  page.drawText(`Fiscal Year: ${input.fiscalYear}`, { x: 60, y: 660, size: 12, font });
  page.drawText(`Amount: JPY ${input.amount.toLocaleString("ja-JP")}`, { x: 60, y: 630, size: 14, font: bold });
  page.drawText(`Paid At: ${input.paidAt ? input.paidAt.toISOString().slice(0, 10) : "-"}`, { x: 60, y: 600, size: 12, font });
  page.drawText("Generated by 学会事務局OS", { x: 60, y: 560, size: 10, font, color: rgb(0.3, 0.3, 0.3) });

  return Buffer.from(await pdf.save());
}
